apiVersion: v1
kind: ConfigMap
metadata:
  name: loadgen-scripts
data:
  loadgen.sh: |
    echo "waiting for consumer to start..."
    while :; do
      if curl -X POST -fs http://localhost:8080/GetCurrentStatus >/dev/null 2>&1; then
        echo "...started"
        break
      fi
      echo "(1 sec)"
      sleep 1
    done
    date
    echo "Sending loadgen request of 500m for 1d"
    curl -s --data "millicores=500&durationSec=86400" http://localhost:8080/ConsumeCPU
    sleep 86400
    exit 0 #to avoid CrashLoopBackoff?
