name: Build and Push Docker image to GHCR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Lint Helm Chart
        run: |
          helm lint charts/optlive-showcase-app

      - name: Publish Helm Chart to GitHub Packages
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_GIT_REPO: optlive-showcase-app
          CR_OWNER: "${{ secrets.TARGET_ORG }}"
          CR_TOKEN: "${{ secrets.GHCR_PAT }}"
        with:
          charts_dir: charts
