name: Build and Push Docker image to GHCR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Lint Helm Chart
        run: |
          helm lint charts/optlive-showcase-app

      - name: Publish Helm Chart
        run: |
          version=$(grep 'version:' charts/optlive-showcase-app/Chart.yaml | awk '{print $2}' | tr -d '"')
          helm package charts/optlive-showcase-app
          helm registry login registry.stormforge.io --username ${{ secrets.SF_HARBOR_USER }} --password ${{ secrets.SF_HARBOR_SECRET }}
          helm push optlive-showcase-app-$version.tgz oci://registry.stormforge.io/examples
